import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Barber Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="[margin:0]">
          <Navbar />
          {children}
          <footer className="flex flex-col items-center text-center [padding:60px_24px]">
          <p>&copy; 2026 Fresh Cuts. All rights reserved.</p>
          </footer>
      </body>
    </html>
  );
}
